Ken/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('',include('django.contrib.auth.urls'))
]

advice/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractUser
from django.utils.timezone import now
from django import forms

from django.db.models import Sum

# Create your models here.

class usernotebook(models.Model):
    user_id = models.BigAutoField(primary_key=True,auto_created=True,serialize=False)
    gender = models.CharField(max_length=15)
    phone = models.CharField(max_length=10)
    profile_pic = models.ImageField(upload_to='images/',blank=True)
    accountlink = models.OneToOneField(User,on_delete=models.CASCADE)

class productitem(models.Model):
    pro_id = models.BigAutoField(primary_key=True,auto_created=True,serialize=False)
    pro_name = models.CharField(max_length=45)
    brand = models.CharField(max_length=45)
    pro_desc = models.CharField(max_length=255,blank=True,)
    price = models.IntegerField(default=0)
    amount = models.CharField(max_length=15,default='instock',blank=True)
    approvedstatus = models.CharField(max_length=15,default='waiting',blank=True)
    date_add = models.DateField(default=now, editable=False)
    pro_pic = models.ImageField(upload_to='images/',blank=True)
    id_link = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.pro_id)


class paymentMethod(models.Model):
    bank_account_number = models.CharField(max_length=45,primary_key=True)
    bank_account = models.CharField(max_length=45)

    def __str__(self):
        return self.bank_account_number

class ordernotebook(models.Model):
    or_id = models.BigAutoField(primary_key=True,auto_created=True,serialize=False)
    date_buy = models.DateField(default=now, editable=False)
    or_sale = models.FloatField(default=0.0)
    u_id = models.ForeignKey(User, on_delete=models.CASCADE,editable=False,default='')
    pro_id = models.ForeignKey(productitem,on_delete=models.CASCADE)
    deli_address = models.CharField(max_length=45,blank=False)
    bank_select = models.ForeignKey(paymentMethod,on_delete=models.CASCADE)
    payslip_pic = models.ImageField(upload_to='payslip/', blank=True)
    status = models.CharField(max_length=45, default='waiting')
    saveyet = models.CharField(max_length=45,default='notyet')

class totaltransaction(models.Model):
    trans_id = models.BigAutoField(primary_key=True,auto_created=True,serialize=False)
    totalsale = models.CharField(max_length=45)
    totalorder = models.CharField(max_length=45)
    date_save = models.DateField(default=now, editable=False)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load sweetify %}
{% sweetify %}
<head>
    <meta charset="UTF-8">
    <title>Notebook Shop</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-5.2.1/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome-6.2.0/css/all.css' %}">
    <script src="{% static 'bootstrap-5.2.1/js/bootstrap.js' %}"></script>
    <script src="{% static 'bootstrap-5.2.1/js/bootstrap.bundle.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Thai&display=swap" rel="stylesheet">
</head>

<style>
    body{
        font-family: 'Noto Sans Thai', sans-serif;
        background-color: #FEF6EB;
    }
    #bloc1, #bloc2
    {
        display:inline;
    }
</style>

<body>
    {% block sidebar %}
        <nav class="navbar navbar-expand-lg navbar-dark sticky-top" style="background-color: #C25B56">
            <div class="container">

                <a class="navbar-brand">
                    <img src="{% static 'image/logo.png' %}" alt="Logo" style="width: 40px" class="rounded-pill">
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'index' %}" style="color: #FEF6EB">หน้าหลัก</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'source' %}">ที่มา</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'objective' %}">จุดประสงค์</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'productshow' %}">สินค้า</a>
                        </li>

                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">ประวัติ</a>
                          <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'proaddhistory' %}"><i class="fa-solid fa-hand-holding-hand"></i> ประวัติการฝากขาย</a></li>
                                <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="{% url 'probuyhistory' %}"><i class="fa-solid fa-cart-shopping"></i> ประวัติการซื้อ</a></li>
                          </ul></li>
                        {% endif %}
                        {% if request.user.is_superuser %}
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">ผู้ดูแล</a>
                          <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'paymentAdd' %}"><i class="fa-solid fa-building-columns"></i> เพิ่มช่องทางชำระเงิน</a></li>
                              <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'ordershow' %}"><i class="fa-solid fa-cash-register"></i> แสดงคำสั่งซื้อ</a></li>
                              <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'totalsalesaveweb' %}"> <i class="fa-solid fa-money-check-dollar"></i> Transaction</a></li>
                          </ul>
                        </li>
                        {% endif %}
                    </ul>
                </div>
                <div>
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            {% if user.is_authenticated %}
                            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" style="color: #FEF6EB">
                                <i class="fa-solid fa-user-gear"></i>&ensp;{{ user.username }}
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'dashboard' %}"><i class="fa-solid fa-right-to-bracket"></i>&ensp;Dashboard</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'logout' %}"><i class="fa-solid fa-user-minus"></i>&ensp;ออกจากระบบ</a></li>
                            </ul>

                            {% else %}
                            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" style="color: #FEF6EB">
                                <i class="fa-solid fa-user-gear"></i>&ensp;เข้าสู่ระบบ
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'login' %}"><i class="fa-solid fa-right-to-bracket"></i>&ensp;ลงชื่อเข้าใช้</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'register' %}"><i class="fa-solid fa-user-plus"></i>&ensp;สมัครมาชิก</a></li>
                            </ul>
                            {% endif %}

                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    {% endblock %}
    {% block content %}
    {% endblock %}
{% block footer %}
    <div class="mt-5 p-4 text-center" style="background-color: #525564; color: #FEF6EB">

                                <img src="{% static 'image/logo.png' %}" alt="Logo" style="width: 50px" class="rounded-pill"> © 2022 Copyright:
            <a style="color: #FEF6EB; text-decoration: none">
                LaptopConsignmentShop.com
            </a>
    </div>
{% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div id="image" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#image" data-bs-slide-to="0" class="active"></button>
            <button type="button" data-bs-target="#image" data-bs-slide-to="1"></button>
            <button type="button" data-bs-target="#image" data-bs-slide-to="2"></button>
        </div>

        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'image/image-home1.jpg' %}" alt="Image Home" class="d-block"
                     style="object-fit:cover; width:100%; height: 500px">
            </div>
            <div class="carousel-item">
                <img src="{% static 'image/image-home2.jpg' %}" alt="Image Home" class="d-block"
                     style="object-fit:cover; width:100%; height: 500px">
            </div>
            <div class="carousel-item">
                <img src="{% static 'image/image-home3.jpg' %}" alt="Image Home" class="d-block"
                     style="object-fit:cover; width:100%; height: 500px">
            </div>
        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#image" data-bs-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#image" data-bs-slide="next">
            <span class="carousel-control-next-icon"></span>
        </button>
    </div>

    <div class="container-fluid pt-5">
        <div class="container pt-5 pb-5">
            <h2 style="color: #C25B56"><b>อยากขายโน๊ตบุ๊คแต่ไม่รู้จะขายที่ไหน สามารถลงขายได้เลย ฟรี!</b></h2>

            <div class="card mt-4">
                <div class="row">
                    <div class="col-lg-8">
                        <img src="{% static 'image/image-home4.jpg' %}" class="img-fluid rounded-start" alt="Image Card"
                             style="object-fit:cover; width:100%; height: 400px">
                    </div>

                    <div class="col-lg-4 mt-4">
                        <div class="card-body">
                            <h5 class="card-title"><b>ลงขายในราคาที่กำหนดเองง่ายๆ ใน 3 ขั้นตอน</b></h5>

                            <div class="row text-center mt-5" style="font-size: 14px">
                                <div class="col-lg-4">
                                    <img src="{% static 'image/register.png' %}" alt="PNG" style="width: 50%">
                                    <h6 class="card-title mt-3"><b>สมัครสมาชิก</b></h6>
                                    <p>
                                        กรอกข้อมูลง่ายๆ<br>
                                        ก็ขายได้
                                    </p>
                                </div>
                                <div class="col-lg-4">
                                    <img src="{% static 'image/info.png' %}" alt="PNG" style="width: 50%">
                                    <h6 class="card-title mt-3"><b>ขาย</b></h6>
                                    <p>ใส่รายละเอียดสินค้า เพื่อลงขาย</p>
                                </div>
                                <div class="col-lg-4">
                                    <img src="{% static 'image/confirm.png' %}" alt="PNG" style="width: 50%">
                                    <h6 class="card-title mt-3"><b>รอผลการยืนยัน</b></h6>
                                    <p>แจ้งผลการยืนยัน ภายใน 24 ชม.</p>
                                </div>

                                <div class="mt-3 d-grid col-lg-7 mx-auto">
                                    <a type="button" class="btn btn-outline-danger btn-lg"
                                       href="{% url 'productconfig' %}">ลงขายเลย</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid pt-5" >
        <div class="container pt-1 pb-5">
            <h2 style="color: #C25B56"><b>ซื้อโน๊ตบุ๊คที่คัดสรรอย่างมีคุณภาพ สามารถซื้อได้เลย ที่นี่!</b></h2>

            <div class="card mt-4">
                <div class="row">
                    <div class="col-lg-4 mt-4">
                        <div class="card-body">
                            <h5 class="card-title"><b>ซื้อสินค้าในราคาที่ต้องการได้ใน 3 ขั้นตอน</b></h5>

                            <div class="row text-center mt-5" style="font-size: 14px">
                                <div class="col-lg-4">
                                    <img src="{% static 'image/register.png' %}" alt="PNG" style="width: 50%">
                                    <h6 class="card-title mt-3"><b>สมัครสมาชิก</b></h6>
                                    <p>
                                        กรอกข้อมูลง่ายๆ<br>
                                        ก็ซื้อได้
                                    </p>
                                </div>
                                <div class="col-lg-4">
                                    <img src="{% static 'image/purchase.png' %}" alt="PNG" style="width: 50%">
                                    <h6 class="card-title mt-3"><b>ซื้อสินค้า</b></h6>
                                    <p>
                                        เลือกซื้อสินค้า<br>
                                        ตามความต้องการ
                                    </p>
                                </div>
                                <div class="col-lg-4">
                                    <img src="{% static 'image/delivery.png' %}" alt="PNG" style="width: 50%">
                                    <h6 class="card-title mt-3"><b>ชำระเงินและจัดส่ง</b></h6>
                                    <p>เลือกวิธีการชำระเงินและใส่ที่อยู่การจัดส่ง</p>
                                </div>

                                <div class="mt-3 d-grid col-lg-7 mx-auto">
                                    <a type="button" class="btn btn-outline-danger btn-lg"
                                       href="{% url 'productshow' %}">ซื้อเลย</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-8">
                        <img src="{% static 'image/image-home5.jpg' %}" class="img-fluid rounded-start" alt="Image Card" style="object-fit:cover; width:100%; height: 400px">
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if not user.is_authenticated %}
    <div class="container-fluid pt-5">
        <div class="container pt-1 text-center">
            <a href="{% url 'register' %}"><img src="{% static 'image/image-home6.jpg' %}" class="img-fluid rounded shadow mb-5" alt="Image Register" style="object-fit:cover; width:100%; height: 400px"></a>
        </div>
    {% endif %}
    </div>
{% endblock %}

templates/ordershow.html
{% extends 'base.html' %}
{% load static %}
{% block content %}<br><br>
<div style="font-size: 36px;text-align: center">คำสั่งซื้อ</div>
<div class="container mt-5">
        <div class="row">
                <div class="card-group">

{% for order in my_data  %}
            <div class="col-md-4">
                <div class="card">
                        {% if order.payslip_pic %}
                        <img class="card-img-top" src="{{ order.payslip_pic.url }}" alt="Card image" style="width:250px;height:250px;margin-left: auto;margin-right: auto">
                        {% else %}
                        <img class="card-img-top" src="{% static 'image/noimage.jpg' %}" alt="Card image" style="width:250px;height:250px;margin-left: auto;margin-right: auto">
                        {% endif %}
                        <div class="card-body pt-0">
                            <p class="card-title">
                        <div class="d-flex justify-content-center ">
                            <div>
                                <div>เลขที่ออเดอร์ ::: {{ order.or_id }}</div>
                                <div>วันที่ ::: {{ order.date_buy }}</div>
                                <div>รหัสสินค้า ::: {{ order.pro_id }}</div>
                                <div>ราคา ::: {{ order.or_sale }}</div>
                                <div>ที่อยู่จัดส่ง ::: {{ order.deli_address }}</div>
                                <div>สถานะ ::: {{ order.status }}</div>
                                <div>ธนาคาร ::: {{ order.bank_select }}</div>
                                <div>ID ผู้ซื้อ ::: {{ order.u_id }}</div>
                                <div><a href="{% url 'showOrder' order.or_id %}" class="btn btn btn-outline-danger mt-3">&ensp;<i class="fa-solid fa-circle-info"></i>&ensp;รายละเอียด</a></div>
                                {% if order.status == 'waiting' %}
                                    <a onclick="EXTREMEchonditionchoicechoiceforadmininordertoapprovedorrejectedorderfromcustomer('{{ order.or_id }}','{{ order.pro_id_id }}')" class="btn btn btn-outline-danger mt-3"><i class="fa-solid fa-xmark"></i>&ensp;จัดการออเดอร์</a>
                                    {% endif %}
                            </div></div>
                        <div class="text-center">
                            <a class="btn btn btn-outline-danger mt-3" style="display: none"><i class="fa-solid fa-check"></i></a>

                        </div>
                    </div>
            </div>
 {% empty %}
    <div class="card">
                        <div class="card-body pt-0">
                            <p class="card-title">
                                <div style="padding: 35px 0;text-align: center;font-size: 46px">ไม่มีออเดอร์</div>


                        </div>
                    </div>
 {% endfor %}
                        </div>
            </div>
        </div>
</div>
    <script>
    function EXTREMEchonditionchoicechoiceforadmininordertoapprovedorrejectedorderfromcustomer(D1,D2){
        Swal.fire({
              title: 'ยอมรับหรือปฏิเสธออเดอร์',
              icon: 'question',
              showDenyButton: true,
              showCancelButton: true,
              confirmButtonText: 'ยืนยัน',
              denyButtonText: `ปฏิเสธ`,
              cancelButtonText:'ยกเลิก'
            }).then((result) => {
              /* Read more about isConfirmed, isDenied below */
              if (result.isConfirmed) {
                Swal.fire({
                title: 'ยืนยันการยอมรับออเดอร์',
                text: "การกระทำต่อไปนี้ ไม่สามารถย้อนคืนได้",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'ยืนยัน',
                cancelButtonText: 'ยกเลิก'
            }).then((result) => {
                if (result.isConfirmed) {
                    try{
                        document.location.href="/ordershow/orderApproved/"+D1+'/'+D2
                        }
                    catch(error)
                        {
                    Swal.fire({
                          icon: 'error',
                          text: 'เกิดข้อผิดพลาด',
                        });
                        }
                }
            })
              } else if (result.isDenied) {
                Swal.fire({
                title: 'ยืนยันการปฏิเสธออเดอร์',
                text: "การกระทำต่อไปนี้ ไม่สามารถย้อนคืนได้",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'ยืนยัน',
                cancelButtonText: 'ยกเลิก'
            }).then((result) => {
                if (result.isConfirmed) {
                    try{
                        document.location.href='/ordershow/Rejected/'+D1;
                        }
                    catch(error)
                        {
                    Swal.fire({
                          icon: 'error',
                          text: 'เกิดข้อผิดพลาด',
                        });
                        }
                }
            })
              }
            })
    }

    </script>
{% endblock %}

templates/p01.html
{% extends "base.html" %}
{% load static %}

{% block content %}

{% endblock %}

templates/payment_add.html
{% extends 'base.html' %}
{% block content %}


    <br><br><br>
    <div class="container bg-white h-auto w-75 bg-light border border-4 "><br>
    <table class="table table-hover text-center" >
        <thead>
            <tr style="background-color: #C25B56;color:white" >
              <th scope="col">บัญชีธนาคาร</th>
              <th scope="col">ชื่อบัญชี ธนาคาร</th>
            </tr>
    </thead>
    <tbody>
        {% for i in showpay %}

    <tr >
      <td>{{ i.bank_account_number }}</td>
      <td>{{ i.bank_account }}</td>
    </tr>

        {% endfor %}
    </tbody>
        </table>
        <center>
            <form method="POST" action='{% url 'paymentAdd' %}' enctype="multipart/form-data">
              {% csrf_token %}

                <br><br>

                <div class="border border-1 w-50">
                    <br>
                    <h4>เพิ่มช่องทางสำหรับชำระเงิน</h4>
                    <br>
                    <div class="form-outline mb-4 w-50">
                    เลขที่ธนาคาร + ชื่อธนาคาร: <br>
                    {{ form.bank_account_number }}
                    {{ form.bank_account_number.errors }}</div>
                    <div class="form-outline mb-4 w-50">
                    ชื่อเจ้าของบัญชีธนาคาร : <br>
                    {{ form.bank_account }}
                    {{ form.bank_account.errors }}</div>
                    <!-- Repeat Password input -->
                    <!-- submit button -->
                    <button type="submit" class="btn btn-primary btn-block mb-4 w-50">เพิ่มช่องทาง</button>

                    <br>
                </div>

            </form>
        </center>
        <br>
    </div>
    <br>
    <br>

{% endblock %}

templates/proaddhistory.html
{% extends 'base.html' %}
{% load static %}
{% block content %}<br><br>
<div style="font-size: 36px;text-align: center">ประวัติการฝากขายสินค้า</div>
<div class="container  mt-5">
        <div class="row">
                <div class="card-group">
{% for order in my_data  %}
            <div class="col-md-4">
            <div class="card">
                        {% if order.pro_pic %}
                        <img class="card-img-top" src="{{ order.pro_pic.url }}" alt="Card image" style="width:250px;height:250px;margin-left: auto;margin-right: auto">
                        {% else %}
                        <img class="card-img-top" src="{% static 'image/noimage.jpg' %}" alt="Card image" style="width:250px;height:250px;margin-left: auto;margin-right: auto">
                        {% endif %}
                        <div class="card-body pt-0">
                            <p class="card-title">
                            <div class="d-flex justify-content-center ">
                            <div>
                                <div>ชื่อสินค้า ::: {{ order.pro_name }}</div>
                                <div>แบรนด์ ::: {{ order.brand }}</div>
                                <div>ราคา ::: {{ order.price }}</div>
                                <div>สถานะ ::: {{ order.approvedstatus }}</div>
                                <div>วันที่ ::: {{ order.date_add }}</div>
                            </div></div>
                            </p>

                        </div>
                    </div>
            </div>
  {% empty %}
    <div class="card">
                        <div class="card-body pt-0">
                            <p class="card-title">
                                <div style="padding: 35px 0;text-align: center;font-size: 46px">ไม่มีประวัติการฝากขาย</div>


                        </div>
                    </div>
 {% endfor %}


                </div>
            </div>
    </div>


{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block content %}
    <br><br><br>
    <div class="container bg-white h-auto w-75 bg-light border border-4 ">
        <center>
            <form method="POST" action='{% url 'register' %}'>
              {% csrf_token %}

                <br><br>

                <div class="border border-1 w-50">
                    <br>
                    <h4>สมัครสมาชิก</h4>
                    <br>
                    <div class="form-outline mb-4 w-50">
                    ชื่อผู้ใช้ :<br>
                    {{ form.username }}
                    {{ form.username.errors }}</div>
                    <!-- Password input -->
                    <div class="form-outline mb-4 w-50">
                    อีเมลล์ :<br>
                    {{ form.email }}
                    {{ form.email.errors }}</div>
                    <div  class="form-outline mb-4 w-50">
                    รหัสผ่าน :<br>
                    {{ form.password1 }}
                    {{ form.password1.errors }}</div>
                    <!-- Password input -->
                    <div class="form-outline mb-4 w-50">
                    ยืนยันรหัสผ่าน :<br>
                    {{ form.password2 }}
                    {{ form.password2.errors }}</div>
                    <!-- Repeat Password input -->
                    <!-- submit button -->
                    <button type="submit" class="btn btn-primary btn-block mb-4 w-50">สมัครสมาชิก</button>
                    <div class="text-center">
                        <p>เป็นสมาชิกอยู่เเล้ว ? <a href="{% url  'login' %}">ล็อคอิน</a></p>
                    </div>
                    <br>
                </div>

            </form>
        </center>
        <br>
    </div>
    <br>
    <br>
{% endblock %}

templates/totalsalesaveweb.html
{% extends 'base.html' %}
{% block content %}




        <br><br><br>
    <div class="container bg-white h-auto w-75 bg-light border border-4 ">



        <center>
            <form method="POST" action='' name='totalsave' enctype="multipart/form-data">
              {% csrf_token %}

                <br><br>

                <div class="border border-1 w-50">
                    <br>
                    <h2>บันทึกการขาย</h2>
                    <br>
                    {% if formcount == 0 %}
                    <div class="form-outline mb-4 w-50" style="font-size: 20px">ไม่มียอดขาย</div>
                    {% else %}
                    <div class="form-outline mb-4 w-50">ยอดขาย ::: {{ form.total }} บาท</div>
                    <div class="form-outline mb-4 w-50">ยอดออเดอร์ ::: {{ formcount }} ออเดอร์</div>

                    <br>
                    <div class="form-outline mb-4 w-50">
                    ยอดขาย<br>
                        <input type="text" name="totalsale" maxlength="45" required="" id="id_totalsale">
                    </div>
                    <!-- Password input -->
                    <div class="form-outline mb-4 w-50">
                    ยอดออเดอร์<br>
                    <input type="text" name="totalorder" maxlength="45" required="" id="id_totalorder">
                    </div>

                    <button type="button" onclick="confirmed()" class="btn btn-primary btn-block mb-4 w-50">บันทึก</button>
                    {% endif %}
                    <br>
                </div>

            </form>
        </center>
        <br>


    <table class="table table-hover text-center" >
        <thead>
            <tr style="background-color: #C25B56;color:white" >
              <th scope="col">ID transaction</th>
              <th scope="col">ยอดขาย</th>
              <th scope="col">จำนวนออเดอร์</th>
              <th scope="col">วันที่บันทึก</th>
            </tr>
    </thead>
    <tbody>
        {% for i in showtransaction %}

    <tr >
      <td>{{ i.trans_id }}</td>
      <td>{{ i.totalsale }}</td>
      <td>{{ i.totalorder }}</td>
      <td>{{ i.date_save }}</td>
    </tr>

        {% endfor %}
    </tbody>
        </table>


    </div>
    <br>
    <br>
    <script type="text/javascript">
        function confirmed(){
            var TOTALSELL = parseFloat(document.getElementById('id_totalsale').value);
            var TOTALORDER = parseFloat(document.getElementById('id_totalorder').value);
            var FORMTOTAL = parseFloat({{ form.total }})
            var FORMCOUNT = parseFloat({{ formcount }})
            var None
            console.log(TOTALSELL,TOTALORDER,FORMTOTAL,FORMCOUNT)
            if (TOTALSELL === FORMTOTAL && TOTALORDER === FORMCOUNT)
            {
                Swal.fire({
                    title: 'ต้องการยืนยันการบันทึกหรือไม่',
                    showDenyButton: true,
                    confirmButtonText: 'บันทึก',
                    denyButtonText: `ไม่บันทึก`,
                }).then((result) => {
                    if (result.isConfirmed) {
                        try {
                            document.totalsave.submit();
                        } catch (error) {
                            Swal.fire({
                                icon: 'error',
                                text: 'เกิดข้อผิดพลาด',
                            });
                        }
                    } else if (result.isDenied) {
                        Swal.fire('ข้อมูลไม่ถูกบันทึก', '', 'info')
                    }
                })
            }
            else if(FORMCOUNT === 0 ){
                Swal.fire({
                        icon: 'error',
                        title: 'ไม่มีออเดอร์',
                        // text: (FORMTOTAL+" != "+TOTALSELL + " , " + {{ formcount }} +" != "+TOTALORDER),
                    }
                )
            }
            else{
                Swal.fire({
                        icon: 'error',
                        title: 'ค่าที่ป้อนไม่ถูกต้อง',
                        // text: (FORMTOTAL+" != "+TOTALSELL + " , " + {{ formcount }} +" != "+TOTALORDER),
                    }
                )
            }
        }
    </script>


{% endblock %}